version: "3.9"

volumes:
  postgres:
  s3:

services:
  kaguya:
    build: ./kaguya
    deploy:
      replicas: 1
    environment:
      AWS_ACCESS_KEY_ID: "eientei"
      AWS_SECRET_ACCESS_KEY: "12345678"

  reisen:
    build: ./reisen
    deploy:
      replicas: 1
    ports:
      - "1323:1323"

  db:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: "eientei"
      POSTGRES_USER: "eientei"
      POSTGRES_DB: "eientei"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  s3:
    image: quay.io/minio/minio
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=eientei
      - MINIO_ROOT_PASSWORD=12345678
    command: "server /data --console-address \":9001\""
    volumes:
      - s3:/data
